CREATE TABLE hitters (
    id serial PRIMARY KEY,
    name text,
    school text,
    years_active text,
    homeruns integer,
    rbis integer,
    batting_average float,
    games_played integer,
    plate_appearances integer,
    at_bats integer,
    hits integer,
    doubles integer,
    triples integer,
    runs integer,
    walks integer,
    strikeouts integer,
    stolen_bases integer,
    on_base_percentage float,
    slugging_percentage float,
    on_base_plus_slugging float,
    extra_base_hits integer,
    total_bases integer,
    hit_by_pitch integer
);